#!/bin/sh
if [[ -z "PURESHELL_ROOT" ]]; then
    echo -e "Error: Please configure PureShell."
    exit 0
fi

pureshell_install () {

    # Set Vars
    PACKAGE=$1

    # Install package
    if ! rpm -qa | grep -qw $PACKAGE; then
        echo -e "\n--- Install ${PACKAGE} ---\n"
        . "${PURESHELL_ROOT}${PURESHELL_PLATFORM}/${PACKAGE}".sh
    else
      echo -e "\n--- ${PACKAGE} already installed ---\n"
    fi
}

pureshell_install $1